[package]
name = "stacio-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60", features = [
    "Win32_Foundation",
    "Win32_Security_Credentials",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_UI_Controls_Dialogs",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
